resources:
  - ../../base

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: nginx

configMapGenerator:
  - name: nginx-html
    behavior: replace
    files:
      - index.html

